/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq.tables.records;


import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Schema;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaRecord extends TableRecordImpl<SchemaRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>schema.version</code>.
     */
    public void setVersion(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>schema.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Schema.SCHEMA.VERSION;
    }

    @Override
    public Integer component1() {
        return getVersion();
    }

    @Override
    public Integer value1() {
        return getVersion();
    }

    @Override
    public SchemaRecord value1(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public SchemaRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchemaRecord
     */
    public SchemaRecord() {
        super(Schema.SCHEMA);
    }

    /**
     * Create a detached, initialised SchemaRecord
     */
    public SchemaRecord(Integer version) {
        super(Schema.SCHEMA);

        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SchemaRecord
     */
    public SchemaRecord(com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Schema value) {
        super(Schema.SCHEMA);

        if (value != null) {
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
