/*
 * This file is generated by jOOQ.
 */
package com.onebytellc.imageviewer.backend.db.jooq;


import com.onebytellc.imageviewer.backend.db.jooq.tables.Collection;
import com.onebytellc.imageviewer.backend.db.jooq.tables.Image;
import com.onebytellc.imageviewer.backend.db.jooq.tables.Path;
import com.onebytellc.imageviewer.backend.db.jooq.tables.Schema;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>collection</code>.
     */
    public static final Collection COLLECTION = Collection.COLLECTION;

    /**
     * The table <code>image</code>.
     */
    public static final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>path</code>.
     */
    public static final Path PATH = Path.PATH;

    /**
     * The table <code>schema</code>.
     */
    public static final Schema SCHEMA = Schema.SCHEMA;
}
