/*
 * This file is generated by jOOQ.
 */
package com.onebytellc.imageviewer.backend.db.jooq.tables.records;


import com.onebytellc.imageviewer.backend.db.jooq.tables.Image;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> implements Record4<Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>image.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>image.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>image.path_id</code>.
     */
    public void setPathId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>image.path_id</code>.
     */
    public Integer getPathId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>image.im_original_date</code>.
     */
    public void setImOriginalDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>image.im_original_date</code>.
     */
    public LocalDateTime getImOriginalDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>image.fs_modify_time</code>.
     */
    public void setFsModifyTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>image.fs_modify_time</code>.
     */
    public LocalDateTime getFsModifyTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Image.IMAGE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Image.IMAGE.PATH_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Image.IMAGE.IM_ORIGINAL_DATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Image.IMAGE.FS_MODIFY_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPathId();
    }

    @Override
    public LocalDateTime component3() {
        return getImOriginalDate();
    }

    @Override
    public LocalDateTime component4() {
        return getFsModifyTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPathId();
    }

    @Override
    public LocalDateTime value3() {
        return getImOriginalDate();
    }

    @Override
    public LocalDateTime value4() {
        return getFsModifyTime();
    }

    @Override
    public ImageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ImageRecord value2(Integer value) {
        setPathId(value);
        return this;
    }

    @Override
    public ImageRecord value3(LocalDateTime value) {
        setImOriginalDate(value);
        return this;
    }

    @Override
    public ImageRecord value4(LocalDateTime value) {
        setFsModifyTime(value);
        return this;
    }

    @Override
    public ImageRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(Integer id, Integer pathId, LocalDateTime imOriginalDate, LocalDateTime fsModifyTime) {
        super(Image.IMAGE);

        setId(id);
        setPathId(pathId);
        setImOriginalDate(imOriginalDate);
        setFsModifyTime(fsModifyTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(com.onebytellc.imageviewer.backend.db.jooq.tables.pojos.Image value) {
        super(Image.IMAGE);

        if (value != null) {
            setId(value.getId());
            setPathId(value.getPathId());
            setImOriginalDate(value.getImOriginalDate());
            setFsModifyTime(value.getFsModifyTime());
            resetChangedOnNotNull();
        }
    }
}
