/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq;


import com.onebyte_llc.imageviewer.backend.db.jooq.tables.CollectionPath;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Directory;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Image;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COLLECTION_PATH_COLLECTION_ID_INDEX = Internal.createIndex(DSL.name("collection_path_collection_id_index"), CollectionPath.COLLECTION_PATH, new OrderField[] { CollectionPath.COLLECTION_PATH.COLLECTION_ID }, false);
    public static final Index DIRECTORY_PATH_INDEX = Internal.createIndex(DSL.name("directory_path_index"), Directory.DIRECTORY, new OrderField[] { Directory.DIRECTORY.PATH }, false);
    public static final Index IMAGE_DIRECTORY_ID_INDEX = Internal.createIndex(DSL.name("image_directory_id_index"), Image.IMAGE, new OrderField[] { Image.IMAGE.DIRECTORY_ID }, false);
}
