/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq;


import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Collection;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.CollectionPath;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Directory;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Image;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.CollectionPathRecord;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.CollectionRecord;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.DirectoryRecord;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.ImageRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CollectionRecord> COLLECTION__PK_COLLECTION = Internal.createUniqueKey(Collection.COLLECTION, DSL.name("pk_collection"), new TableField[] { Collection.COLLECTION.ID }, true);
    public static final UniqueKey<CollectionPathRecord> COLLECTION_PATH__PK_COLLECTION_PATH = Internal.createUniqueKey(CollectionPath.COLLECTION_PATH, DSL.name("pk_collection_path"), new TableField[] { CollectionPath.COLLECTION_PATH.ID }, true);
    public static final UniqueKey<DirectoryRecord> DIRECTORY__PK_DIRECTORY = Internal.createUniqueKey(Directory.DIRECTORY, DSL.name("pk_directory"), new TableField[] { Directory.DIRECTORY.ID }, true);
    public static final UniqueKey<DirectoryRecord> DIRECTORY__UK_DIRECTORY_97053330 = Internal.createUniqueKey(Directory.DIRECTORY, DSL.name("uk_directory_97053330"), new TableField[] { Directory.DIRECTORY.PATH }, true);
    public static final UniqueKey<ImageRecord> IMAGE__PK_IMAGE = Internal.createUniqueKey(Image.IMAGE, DSL.name("pk_image"), new TableField[] { Image.IMAGE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CollectionPathRecord, CollectionRecord> COLLECTION_PATH__FK_COLLECTION_ID = Internal.createForeignKey(CollectionPath.COLLECTION_PATH, DSL.name("fk_collection_id"), new TableField[] { CollectionPath.COLLECTION_PATH.COLLECTION_ID }, Keys.COLLECTION__PK_COLLECTION, new TableField[] { Collection.COLLECTION.ID }, true);
    public static final ForeignKey<ImageRecord, DirectoryRecord> IMAGE__FK_DIRECTORY_ID = Internal.createForeignKey(Image.IMAGE, DSL.name("fk_directory_id"), new TableField[] { Image.IMAGE.DIRECTORY_ID }, Keys.DIRECTORY__PK_DIRECTORY, new TableField[] { Directory.DIRECTORY.ID }, true);
}
