/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq;


import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Collection;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.CollectionPath;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Directory;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Image;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Schema;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>collection</code>.
     */
    public static final Collection COLLECTION = Collection.COLLECTION;

    /**
     * The table <code>collection_path</code>.
     */
    public static final CollectionPath COLLECTION_PATH = CollectionPath.COLLECTION_PATH;

    /**
     * The table <code>directory</code>.
     */
    public static final Directory DIRECTORY = Directory.DIRECTORY;

    /**
     * The table <code>image</code>.
     */
    public static final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>schema</code>.
     */
    public static final Schema SCHEMA = Schema.SCHEMA;
}
