/*
 * This file is generated by jOOQ.
 */
package com.onebytellc.imageviewer.backend.db.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Directory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String path;

    public Directory() {}

    public Directory(Directory value) {
        this.id = value.id;
        this.path = value.path;
    }

    public Directory(
        Integer id,
        String path
    ) {
        this.id = id;
        this.path = path;
    }

    /**
     * Getter for <code>directory.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>directory.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>directory.path</code>.
     */
    public String getPath() {
        return this.path;
    }

    /**
     * Setter for <code>directory.path</code>.
     */
    public void setPath(String path) {
        this.path = path;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Directory other = (Directory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.path == null) {
            if (other.path != null)
                return false;
        }
        else if (!this.path.equals(other.path))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.path == null) ? 0 : this.path.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Directory (");

        sb.append(id);
        sb.append(", ").append(path);

        sb.append(")");
        return sb.toString();
    }
}
