/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq.tables;


import com.onebyte_llc.imageviewer.backend.db.jooq.DefaultSchema;
import com.onebyte_llc.imageviewer.backend.db.jooq.Keys;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.CollectionRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Collection extends TableImpl<CollectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>collection</code>
     */
    public static final Collection COLLECTION = new Collection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CollectionRecord> getRecordType() {
        return CollectionRecord.class;
    }

    /**
     * The column <code>collection.id</code>.
     */
    public final TableField<CollectionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>collection.name</code>.
     */
    public final TableField<CollectionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    private Collection(Name alias, Table<CollectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Collection(Name alias, Table<CollectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>collection</code> table reference
     */
    public Collection(String alias) {
        this(DSL.name(alias), COLLECTION);
    }

    /**
     * Create an aliased <code>collection</code> table reference
     */
    public Collection(Name alias) {
        this(alias, COLLECTION);
    }

    /**
     * Create a <code>collection</code> table reference
     */
    public Collection() {
        this(DSL.name("collection"), null);
    }

    public <O extends Record> Collection(Table<O> child, ForeignKey<O, CollectionRecord> key) {
        super(child, key, COLLECTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CollectionRecord> getPrimaryKey() {
        return Keys.COLLECTION__PK_COLLECTION;
    }

    @Override
    public Collection as(String alias) {
        return new Collection(DSL.name(alias), this);
    }

    @Override
    public Collection as(Name alias) {
        return new Collection(alias, this);
    }

    @Override
    public Collection as(Table<?> alias) {
        return new Collection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Collection rename(String name) {
        return new Collection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Collection rename(Name name) {
        return new Collection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Collection rename(Table<?> name) {
        return new Collection(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
