/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq.tables;


import com.onebyte_llc.imageviewer.backend.db.jooq.DefaultSchema;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.SchemaRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schema extends TableImpl<SchemaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>schema</code>
     */
    public static final Schema SCHEMA = new Schema();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SchemaRecord> getRecordType() {
        return SchemaRecord.class;
    }

    /**
     * The column <code>schema.version</code>.
     */
    public final TableField<SchemaRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    private Schema(Name alias, Table<SchemaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Schema(Name alias, Table<SchemaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>schema</code> table reference
     */
    public Schema(String alias) {
        this(DSL.name(alias), SCHEMA);
    }

    /**
     * Create an aliased <code>schema</code> table reference
     */
    public Schema(Name alias) {
        this(alias, SCHEMA);
    }

    /**
     * Create a <code>schema</code> table reference
     */
    public Schema() {
        this(DSL.name("schema"), null);
    }

    public <O extends Record> Schema(Table<O> child, ForeignKey<O, SchemaRecord> key) {
        super(child, key, SCHEMA);
    }

    @Override
    public org.jooq.Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Schema as(String alias) {
        return new Schema(DSL.name(alias), this);
    }

    @Override
    public Schema as(Name alias) {
        return new Schema(alias, this);
    }

    @Override
    public Schema as(Table<?> alias) {
        return new Schema(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Schema rename(String name) {
        return new Schema(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schema rename(Name name) {
        return new Schema(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Schema rename(Table<?> name) {
        return new Schema(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
