/*
 * This file is generated by jOOQ.
 */
package com.onebyte_llc.imageviewer.backend.db.jooq.tables.daos;


import com.onebyte_llc.imageviewer.backend.db.jooq.tables.Directory;
import com.onebyte_llc.imageviewer.backend.db.jooq.tables.records.DirectoryRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryDao extends DAOImpl<DirectoryRecord, com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory, Integer> {

    /**
     * Create a new DirectoryDao without any configuration
     */
    public DirectoryDao() {
        super(Directory.DIRECTORY, com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory.class);
    }

    /**
     * Create a new DirectoryDao with an attached configuration
     */
    public DirectoryDao(Configuration configuration) {
        super(Directory.DIRECTORY, com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory.class, configuration);
    }

    @Override
    public Integer getId(com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Directory.DIRECTORY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchById(Integer... values) {
        return fetch(Directory.DIRECTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory fetchOneById(Integer value) {
        return fetchOne(Directory.DIRECTORY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchOptionalById(Integer value) {
        return fetchOptional(Directory.DIRECTORY.ID, value);
    }

    /**
     * Fetch records that have <code>path BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchRangeOfPath(String lowerInclusive, String upperInclusive) {
        return fetchRange(Directory.DIRECTORY.PATH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>path IN (values)</code>
     */
    public List<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchByPath(String... values) {
        return fetch(Directory.DIRECTORY.PATH, values);
    }

    /**
     * Fetch a unique record that has <code>path = value</code>
     */
    public com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory fetchOneByPath(String value) {
        return fetchOne(Directory.DIRECTORY.PATH, value);
    }

    /**
     * Fetch a unique record that has <code>path = value</code>
     */
    public Optional<com.onebyte_llc.imageviewer.backend.db.jooq.tables.pojos.Directory> fetchOptionalByPath(String value) {
        return fetchOptional(Directory.DIRECTORY.PATH, value);
    }
}
